# Site settings
title: Jason Green
email: jason@jasongreen.net
author: Jason Green
description: "An Exercise in Digital Identity"
baseurl: "/pixyll"
url: "http://github.com/jasonkgreen"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
paginate_path: "blog/"
sass:
  compressed: true
