# Site settings
title: Jason Green
email: your_email@example.com
author: Jason Green
description: "an exercise in digital identity"
baseurl: "/pixyll"
url: "http://jasonkgreen.github.io"
# google_analytics: UA-53548208-1
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
