# Site settings
title: Jason Green
email: jason@jasongreen.net
author: Jason Green
description: "An Exercise in Digital Identity"
baseurl: ""
url: "http://www.jasongreen.net"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
